-- HR modules: availability, leave, documents, notifications, expenses, payroll runs, profile fields

ALTER TABLE public.staff
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS emergency_contact text,
  ADD COLUMN IF NOT EXISTS date_of_birth date,
  ADD COLUMN IF NOT EXISTS national_insurance text,
  ADD COLUMN IF NOT EXISTS nationality text,
  ADD COLUMN IF NOT EXISTS gender text,
  ADD COLUMN IF NOT EXISTS start_date date,
  ADD COLUMN IF NOT EXISTS end_date date,
  ADD COLUMN IF NOT EXISTS salary numeric(12,2),
  ADD COLUMN IF NOT EXISTS tax_code text,
  ADD COLUMN IF NOT EXISTS ni_category text,
  ADD COLUMN IF NOT EXISTS bank_sort_code text,
  ADD COLUMN IF NOT EXISTS bank_account_last4 text;

CREATE TABLE IF NOT EXISTS public.staff_availability (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  staff_id bigint NOT NULL REFERENCES public.staff(id) ON DELETE CASCADE,
  weekday smallint,
  specific_date date,
  start_time time NOT NULL,
  end_time time NOT NULL,
  status text NOT NULL DEFAULT 'available',
  is_recurring boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT staff_availability_status_check CHECK (
    status = ANY (ARRAY['available','preferred','unavailable','holiday','not_set']::text[])
  ),
  CONSTRAINT staff_availability_weekday_check CHECK (weekday IS NULL OR (weekday >= 0 AND weekday <= 6)),
  CONSTRAINT staff_availability_slot_check CHECK (end_time > start_time)
);

CREATE INDEX IF NOT EXISTS idx_staff_availability_user ON public.staff_availability(user_id);
CREATE INDEX IF NOT EXISTS idx_staff_availability_staff ON public.staff_availability(staff_id);
CREATE INDEX IF NOT EXISTS idx_staff_availability_date ON public.staff_availability(specific_date);

CREATE TABLE IF NOT EXISTS public.leave_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  staff_id bigint NOT NULL REFERENCES public.staff(id) ON DELETE CASCADE,
  start_date date NOT NULL,
  end_date date NOT NULL,
  category text NOT NULL DEFAULT 'paid_leave',
  hours numeric(8,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending',
  notes text,
  reviewer_staff_id bigint REFERENCES public.staff(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  review_notes text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT leave_requests_category_check CHECK (
    category = ANY (ARRAY['paid_leave','unpaid_leave','sick_leave','maternity','paternity','compassionate','study','other']::text[])
  ),
  CONSTRAINT leave_requests_status_check CHECK (
    status = ANY (ARRAY['pending','approved','rejected','cancelled']::text[])
  ),
  CONSTRAINT leave_requests_dates_check CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_leave_requests_user ON public.leave_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_staff ON public.leave_requests(staff_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status ON public.leave_requests(status);

CREATE TABLE IF NOT EXISTS public.staff_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  staff_id bigint NOT NULL REFERENCES public.staff(id) ON DELETE CASCADE,
  doc_type text NOT NULL,
  file_name text NOT NULL,
  mime_type text,
  file_data text,
  expires_at date,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_staff_documents_user ON public.staff_documents(user_id);
CREATE INDEX IF NOT EXISTS idx_staff_documents_staff ON public.staff_documents(staff_id);
CREATE INDEX IF NOT EXISTS idx_staff_documents_expires ON public.staff_documents(expires_at);

CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  staff_id bigint REFERENCES public.staff(id) ON DELETE CASCADE,
  type text NOT NULL,
  title text NOT NULL,
  body text,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_staff ON public.notifications(staff_id);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON public.notifications(user_id) WHERE read_at IS NULL;

CREATE TABLE IF NOT EXISTS public.expenses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  staff_id bigint NOT NULL REFERENCES public.staff(id) ON DELETE CASCADE,
  category text NOT NULL,
  amount numeric(12,2) NOT NULL,
  expense_date date NOT NULL DEFAULT CURRENT_DATE,
  description text,
  receipt_file_name text,
  receipt_data text,
  status text NOT NULL DEFAULT 'pending',
  reviewer_staff_id bigint REFERENCES public.staff(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  review_notes text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT expenses_status_check CHECK (
    status = ANY (ARRAY['pending','approved','rejected','reimbursed']::text[])
  ),
  CONSTRAINT expenses_amount_check CHECK (amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_expenses_user ON public.expenses(user_id);
CREATE INDEX IF NOT EXISTS idx_expenses_staff ON public.expenses(staff_id);
CREATE INDEX IF NOT EXISTS idx_expenses_status ON public.expenses(status);

CREATE TABLE IF NOT EXISTS public.payroll_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  period_start date NOT NULL,
  period_end date NOT NULL,
  schedule_type text NOT NULL DEFAULT 'monthly',
  status text NOT NULL DEFAULT 'draft',
  total_gross numeric(12,2) NOT NULL DEFAULT 0,
  notes text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT payroll_runs_schedule_check CHECK (
    schedule_type = ANY (ARRAY['weekly','fortnightly','four_weekly','monthly']::text[])
  ),
  CONSTRAINT payroll_runs_status_check CHECK (
    status = ANY (ARRAY['draft','finalized','paid']::text[])
  )
);

CREATE INDEX IF NOT EXISTS idx_payroll_runs_user ON public.payroll_runs(user_id);

CREATE TABLE IF NOT EXISTS public.payslips (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_run_id bigint NOT NULL REFERENCES public.payroll_runs(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  staff_id bigint NOT NULL REFERENCES public.staff(id) ON DELETE CASCADE,
  gross_pay numeric(12,2) NOT NULL DEFAULT 0,
  net_pay numeric(12,2) NOT NULL DEFAULT 0,
  hours_worked numeric(10,2) NOT NULL DEFAULT 0,
  line_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payslips_run ON public.payslips(payroll_run_id);
CREATE INDEX IF NOT EXISTS idx_payslips_staff ON public.payslips(staff_id);

CREATE TABLE IF NOT EXISTS public.rota_publishes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  week_start date NOT NULL,
  published_by_user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
  published_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT rota_publishes_user_week_key UNIQUE (user_id, week_start)
);

CREATE INDEX IF NOT EXISTS idx_rota_publishes_user ON public.rota_publishes(user_id);

ALTER TABLE public.shifts
  ADD COLUMN IF NOT EXISTS published_at timestamptz;

DROP TRIGGER IF EXISTS update_staff_availability_updated_at ON public.staff_availability;
CREATE TRIGGER update_staff_availability_updated_at
  BEFORE UPDATE ON public.staff_availability
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_leave_requests_updated_at ON public.leave_requests;
CREATE TRIGGER update_leave_requests_updated_at
  BEFORE UPDATE ON public.leave_requests
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_staff_documents_updated_at ON public.staff_documents;
CREATE TRIGGER update_staff_documents_updated_at
  BEFORE UPDATE ON public.staff_documents
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_expenses_updated_at ON public.expenses;
CREATE TRIGGER update_expenses_updated_at
  BEFORE UPDATE ON public.expenses
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_payroll_runs_updated_at ON public.payroll_runs;
CREATE TRIGGER update_payroll_runs_updated_at
  BEFORE UPDATE ON public.payroll_runs
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
