CREATE TABLE IF NOT EXISTS public.escalation_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  staff_id bigint REFERENCES public.staff(id) ON DELETE SET NULL,
  category text NOT NULL,
  severity text NOT NULL DEFAULT 'medium',
  status text NOT NULL DEFAULT 'open',
  description text NOT NULL,
  is_anonymous boolean NOT NULL DEFAULT false,
  witnesses text,
  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
  manager_notes text,
  actions_taken text,
  timeline jsonb NOT NULL DEFAULT '[]'::jsonb,
  follow_up_date date,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT escalation_reports_category_check CHECK (
    category = ANY (ARRAY[
      'bullying','harassment','health_safety','payroll_issue','discrimination',
      'equipment_issue','shift_concern','manager_concern','whistleblowing','other'
    ]::text[])
  ),
  CONSTRAINT escalation_reports_severity_check CHECK (
    severity = ANY (ARRAY['low','medium','high','critical']::text[])
  ),
  CONSTRAINT escalation_reports_status_check CHECK (
    status = ANY (ARRAY['open','investigating','resolved','escalated']::text[])
  )
);

CREATE INDEX IF NOT EXISTS idx_escalation_reports_user ON public.escalation_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_escalation_reports_staff ON public.escalation_reports(staff_id);
CREATE INDEX IF NOT EXISTS idx_escalation_reports_status ON public.escalation_reports(status);

DROP TRIGGER IF EXISTS update_escalation_reports_updated_at ON public.escalation_reports;
CREATE TRIGGER update_escalation_reports_updated_at
  BEFORE UPDATE ON public.escalation_reports
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
