-- Company hierarchy for departments, branches, manager assignment, and staff transfers.
CREATE TABLE IF NOT EXISTS public.branches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    name text NOT NULL,
    address text,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT branches_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
    CONSTRAINT branches_user_name_key UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS public.departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL,
    name text NOT NULL,
    description text,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT departments_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
    CONSTRAINT departments_user_name_key UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS public.staff_assignment_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    staff_id bigint NOT NULL REFERENCES public.staff(id) ON DELETE CASCADE,
    from_department_id bigint REFERENCES public.departments(id) ON DELETE SET NULL,
    to_department_id bigint REFERENCES public.departments(id) ON DELETE SET NULL,
    from_branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL,
    to_branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL,
    from_manager_id bigint REFERENCES public.staff(id) ON DELETE SET NULL,
    to_manager_id bigint REFERENCES public.staff(id) ON DELETE SET NULL,
    reason text,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.staff
  ADD COLUMN IF NOT EXISTS department_id bigint REFERENCES public.departments(id) ON DELETE SET NULL;

ALTER TABLE public.staff
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;

ALTER TABLE public.staff
  ADD COLUMN IF NOT EXISTS manager_id bigint REFERENCES public.staff(id) ON DELETE SET NULL;

ALTER TABLE public.staff
  ADD COLUMN IF NOT EXISTS access_role text NOT NULL DEFAULT 'employee';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'staff_access_role_check'
      AND conrelid = 'public.staff'::regclass
  ) THEN
    ALTER TABLE public.staff
      ADD CONSTRAINT staff_access_role_check
      CHECK (access_role = ANY (ARRAY['employee'::text, 'manager'::text, 'payroll_admin'::text]));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_branches_user_id ON public.branches(user_id);
CREATE INDEX IF NOT EXISTS idx_departments_user_id ON public.departments(user_id);
CREATE INDEX IF NOT EXISTS idx_departments_branch_id ON public.departments(branch_id);
CREATE INDEX IF NOT EXISTS idx_staff_department_id ON public.staff(department_id);
CREATE INDEX IF NOT EXISTS idx_staff_branch_id ON public.staff(branch_id);
CREATE INDEX IF NOT EXISTS idx_staff_manager_id ON public.staff(manager_id);
CREATE INDEX IF NOT EXISTS idx_staff_access_role ON public.staff(access_role);
CREATE INDEX IF NOT EXISTS idx_staff_assignment_history_staff_id ON public.staff_assignment_history(staff_id);

DROP TRIGGER IF EXISTS update_branches_updated_at ON public.branches;
CREATE TRIGGER update_branches_updated_at
  BEFORE UPDATE ON public.branches
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_departments_updated_at ON public.departments;
CREATE TRIGGER update_departments_updated_at
  BEFORE UPDATE ON public.departments
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
